"""`ai-workflow adopt` — legacy repo adoption (spec §10, TICKET-005).

Performs the mechanical first steps of adoption and Hands the judgment steps to
a senior model via `workflow-bootstrap` / `MIGRATION.md`:

    discovery -> migration report -> state.yaml scaffold carrying the
    migration / historical_phases / adoption_checkpoint blocks.

Idempotent and non-destructive: never deletes and never overwrites an existing
file (a second run on an already-adopted ticket is a no-op). It does not fabricate
history: historical phases are scaffolded as `not_performed` and
`adoption_checkpoint.continuation_safe` stays `false` until a senior confirms the
six checkpoint items.
"""

import os
import subprocess

import state
import validate

__all__ = ["adopt", "MIGRATION_REPORT_NAME"]

MIGRATION_REPORT_NAME = "migration-report.md"
_WORK_DIR_REL = os.path.join(".ai", "work")


def _kit_root():
    # this file: scripts/ai-workflow/adopt.py
    return os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _template_dir():
    return os.path.join(_kit_root(), ".ai", "workflow", "templates")


def _git(root, *args):
    try:
        out = subprocess.run(
            ["git", "-C", root, *args], capture_output=True, text=True, timeout=10
        )
        if out.returncode == 0:
            return out.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        pass
    return None


def _discover(root):
    """Collect repository facts (not conclusions) for the migration report."""
    facts = {}
    facts["is_git_repo"] = _git(root, "rev-parse", "--is-inside-work-tree") == "true"
    facts["branch"] = _git(root, "rev-parse", "--abbrev-ref", "HEAD")
    facts["head"] = _git(root, "rev-parse", "HEAD")
    porcelain = _git(root, "status", "--porcelain")
    dirty = porcelain.splitlines() if porcelain else []
    facts["dirty"] = bool(dirty)
    facts["dirty_count"] = len(dirty)
    facts["dirty_files"] = dirty[:20]
    log = _git(root, "log", "--oneline", "-n", "10")
    facts["recent_commits"] = log.splitlines() if log else []

    # File presence probes (mechanically reportable). Content judgment is senior's.
    probes = {
        "AGENTS.md": os.path.exists(os.path.join(root, "AGENTS.md")),
        "README": any(os.path.exists(os.path.join(root, n))
                      for n in ("README", "README.md", "README.txt")),
        "docs/": os.path.isdir(os.path.join(root, "docs")),
        ".ai/workflow/": os.path.isdir(os.path.join(root, ".ai", "workflow")),
        ".agents/": os.path.isdir(os.path.join(root, ".agents")),
        ".scratch/ (tickets/issues)": (
            os.path.isdir(os.path.join(root, ".scratch")) or _has_scratch(root)
        ),
    }
    facts["probes"] = probes

    managed = False
    agents_path = os.path.join(root, "AGENTS.md")
    if os.path.exists(agents_path):
        try:
            with open(agents_path, encoding="utf-8") as fh:
                managed = "<!-- BEGIN AI-WORKFLOW -->" in fh.read()
        except OSError:
            managed = False
    facts["managed_block"] = managed

    test_markers = []
    for probe in ("test", "tests", "spec", "__tests__"):
        if os.path.isdir(os.path.join(root, probe)):
            test_markers.append(probe)
    facts["test_dirs"] = test_markers
    return facts


def _has_scratch(root):
    scratch = os.path.join(root, ".scratch")
    if not os.path.isdir(scratch):
        return False
    for dirpath, _dirs, files in os.walk(scratch):
        for fname in files:
            if fname.endswith(".md"):
                return True
    return False


def _write_file_once(path, text, created):
    if os.path.exists(path):
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    created.append(path)


def _migration_report(root, facts):
    lines = []
    lines.append("# Migration Report")
    lines.append("")
    lines.append("Generated by `ai-workflow adopt` (mechanically; a senior must")
    lines.append("confirm the facts and drive the judgment steps that follow).")
    lines.append("")
    lines.append("## Discovery")
    lines.append("")
    lines.append("- Git repo: %s" % ("yes" if facts["is_git_repo"] else "no"))
    lines.append("- Branch: %s" % (facts["branch"] or "n/a"))
    lines.append("- HEAD: %s" % (facts["head"] or "n/a"))
    lines.append("- Uncommitted work: %s" %
                 ("" if facts["dirty"] else "clean"))
    for f in facts["dirty_files"]:
        lines.append("  - `%s`" % f)
    lines.append("- Recent commits:")
    if facts["recent_commits"]:
        for c in facts["recent_commits"]:
            lines.append("  - `%s`" % c)
    else:
        lines.append("  - (none)")
    lines.append("- Managed block in AGENTS.md: %s" %
                 ("present" if facts["managed_block"] else "absent"))
    lines.append("- Test dirs present: %s" % (", ".join(facts["test_dirs"]) or "none"))
    lines.append("- File probes:")
    for name, present in facts["probes"].items():
        lines.append("  - %s: %s" % (name, "present" if present else "absent"))
    lines.append("")
    lines.append("## Required next steps (senior, per MIGRATION.md)")
    lines.append("")
    steps = [
        "Review this report; correct any discovery facts.",
        "Phase reconstruction: mark `historical_phases` as confirmed/inferred/"
        "existing/not_performed, with anchors where confirmed.",
        "Retroactive minimum evidence into evidence.md with a Migration Notice.",
        "Decision reconstruction (only still-valid decisions) with Provenance.",
        "Confirm the six adoption_checkpoint items; set continuation_safe: true.",
        "Run `ai-workflow validate <ticket>` — it must pass before handoff.",
    ]
    for i, s in enumerate(steps, 1):
        lines.append("%d. %s" % (i, s))
    lines.append("")
    return "\n".join(lines)


def _build_state(ticket_id, title, phase, base_commit, branch,
                 spec_path, ticket_path, plan_path):
    ph = phase if phase in validate.PHASES else "requirement"
    return {
        "schema_version": 1,
        "workflow_version": 1,
        "ticket": {"id": ticket_id, "title": title or ""},
        "phase": ph,
        "status": "active",
        "repository": {"base_commit": base_commit, "branch": branch},
        "source_artifacts": {
            "spec": {"path": spec_path},
            "ticket": {"path": ticket_path},
            "plan": {"path": plan_path},
        },
        "artifacts": {
            "evidence": "evidence.md",
            "evidence_audit": "evidence-audit.md",
            "decision": "decision.md",
            "progress": "progress.md",
            "handoff": "handoff.md",
        },
        "evidence": {"round": 0, "gate": "insufficient"},
        "implementation": {"current_task": 0, "total_tasks": 0, "completed_tasks": []},
        "escalation": {"required": False, "scope": "machine", "reason": None},
        "claim": {"harness": None, "model": None, "claimed_at": None},
        "next_action": {
            "role": "workflow-bootstrap",
            "action": "senior: complete adoption then confirm adoption checkpoint per MIGRATION.md",
            "task": None,
        },
        "provenance": {"last_harness": None, "last_model": None},
        "migration": {
            "adopted_existing_repo": True,
            "adopted_at_phase": ph,
        },
        "historical_phases": {
            p: {"status": "not_performed"} for p in validate.PHASES
        },
        "adoption_checkpoint": {
            "repository_understood": False,
            "active_ticket_identified": False,
            "current_phase_identified": False,
            "remaining_work_identified": False,
            "critical_invariants_identified": False,
            "continuation_safe": False,
        },
    }


def _scaffold_template(dst_path, name, created, ticket_id=None):
    """Copy a bundled template into dst_path if absent (idempotent)."""
    if os.path.exists(dst_path):
        return
    src = os.path.join(_template_dir(), name)
    try:
        with open(src, encoding="utf-8") as fh:
            text = fh.read()
    except OSError:
        text = "# %s\n" % name
    text = text.replace("<ticket-id>", ticket_id or "<ticket-id>")
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, "w", encoding="utf-8") as fh:
        fh.write(text)
    created.append(dst_path)


def adopt(root, ticket_id, phase=None, title=None,
          spec_path=None, ticket_path=None, plan_path=None,
          base_commit=None, branch=None):
    """Adopt an existing/legacy repo into the workflow.

    Creates `.ai/migration-report.md` and scaffolds `.ai/work/<ticket-id>/`
    (state.yaml with the migration / historical_phases / adoption_checkpoint
    blocks, plus evidence/handoff/progress). Returns created paths; a no-op if
    the ticket is already adopted.
    """
    created = []

    # 1. Migration report (never overwrite).
    _write_file_once(
        os.path.join(root, ".ai", MIGRATION_REPORT_NAME),
        _migration_report(root, _discover(root)),
        created,
    )

    # 2. State scaffold (never overwrite an existing adoption).
    work_dir = os.path.join(root, _WORK_DIR_REL, ticket_id)
    state_path = os.path.join(work_dir, "state.yaml")
    if os.path.exists(state_path):
        return created  # already adopted; idempotent no-op

    os.makedirs(work_dir, exist_ok=True)

    base_commit = base_commit or _git(root, "rev-parse", "HEAD")
    branch = branch or _git(root, "rev-parse", "--abbrev-ref", "HEAD")

    data = _build_state(
        ticket_id, title, phase, base_commit, branch,
        spec_path, ticket_path, plan_path,
    )
    state.save_file(state_path, data)
    created.append(state_path)

    # 3. Operational artifact scaffolds (evidence/handoff/progress). decision.md
    #    is reconstructed by the senior during adoption and is not fake-started
    #    here; evidence-audit.md comes when evidence is audited.
    _scaffold_template(os.path.join(work_dir, "evidence.md"), "evidence.md", created, ticket_id)
    _scaffold_template(os.path.join(work_dir, "handoff.md"), "handoff.md", created, ticket_id)
    _scaffold_template(os.path.join(work_dir, "progress.md"), "progress.md", created, ticket_id)

    return created